# Generated by Django 6.0.2 on 2026-06-21 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectProfile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=255)),
                ('sector', models.CharField(blank=True, max_length=120, null=True)),
                ('lang_preference', models.CharField(choices=[('fr', 'French'), ('ar', 'Arabic')])),
                ('self_assessed_stage', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ProfileLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(choices=[('intake', 'Intake Engine'), ('diagnostic', 'Diagnostic Engine'), ('market', 'Market Scoring Engine'), ('commercial', 'Commercial Scoring Engine'), ('innovation', 'Innovation Scoring Engine'), ('scaling', 'Scaling Scoring Engine'), ('green', 'Green Scoring Engine'), ('unifier', 'Unified Assessment Layer'), ('roadmap', 'Roadmap Engine'), ('assistant', 'Grounded Assistant')], max_length=30)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('output_type', models.CharField(blank=True, default='', max_length=200)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='projects.projectprofile')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
