# Generated by Django 6.0.2 on 2026-06-23 15:57

import projects.fields
from django.db import migrations


def encrypt_existing_names(apps, schema_editor):
    ProjectProfile = apps.get_model('projects', 'ProjectProfile')
    for profile in ProjectProfile.objects.all().iterator():
        fields_to_update = ['project_name']

        metadata = profile.metadata if isinstance(profile.metadata, dict) else {}
        if 'gerant' in metadata:
            gerant_value = metadata.pop('gerant')
            profile.metadata = metadata
            fields_to_update.append('metadata')
            if gerant_value not in (None, ''):
                profile.gerant_name = gerant_value
                fields_to_update.append('gerant_name')

        profile.project_name = profile.project_name
        profile.save(update_fields=fields_to_update)


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectprofile',
            name='gerant_name',
            field=projects.fields.EncryptedTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projectprofile',
            name='project_name',
            field=projects.fields.EncryptedTextField(),
        ),
        migrations.RunPython(encrypt_existing_names, migrations.RunPython.noop),
    ]
