# Generated by Django 6.0.2 on 2026-06-23 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_projectprofile_gerant_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectprofile',
            name='roadmap',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
