# Generated by Django 6.0.2 on 2026-06-23 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_projectprofile_roadmap'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectprofile',
            name='gerant_name',
        ),
        migrations.RemoveField(
            model_name='projectprofile',
            name='project_name',
        ),
    ]
